

CREATE ALGORITHM=UNDEFINED DEFINER=`impact`@`%` SQL SECURITY DEFINER VIEW `EE3_5`.`lemmata_and_wordforms` AS select `a`.`modern_lemma` AS `modern_lemma`,`a`.`lemma_part_of_speech` AS `lemma_part_of_speech`,`b`.`wordform` AS `wordform`,`c`.`part_of_speech` AS `part_of_speech` from ((`EE3_5`.`lemmata` `a` join `EE3_5`.`wordforms` `b`) join `EE3_5`.`analyzed_wordforms` `c`) where ((`a`.`lemma_id` = `c`.`lemma_id`) and (`b`.`wordform_id` = `c`.`wordform_id`));



CREATE ALGORITHM=UNDEFINED DEFINER=`impact`@`%` SQL SECURITY DEFINER 
VIEW 
	`EE3_5`.`lemmata_and_wordforms_complete` 
AS (select 'single' AS `mode`,`EE3_5`.`lemmata`.`modern_lemma` AS `modern_lemma`,`EE3_5`.`lemmata`.`lemma_part_of_speech` AS `lemma_part_of_speech`,if(isnull(`EE3_5`.`wordforms`.`wordform`),'',`EE3_5`.`wordforms`.`wordform`) AS `wordform`,if(isnull(`EE3_5`.`derivations`.`normalized_form`),'',`EE3_5`.`derivations`.`normalized_form`) AS `normalized_form` 
from (((`EE3_5`.`lemmata` left join `EE3_5`.`analyzed_wordforms` on(((`EE3_5`.`analyzed_wordforms`.`multiple_lemmata_analysis_id` = 0) and (`EE3_5`.`analyzed_wordforms`.`lemma_id` = `EE3_5`.`lemmata`.`lemma_id`)))) left join `EE3_5`.`wordforms` on((`EE3_5`.`analyzed_wordforms`.`wordform_id` = `EE3_5`.`wordforms`.`wordform_id`))) left join `EE3_5`.`derivations` on((`EE3_5`.`analyzed_wordforms`.`derivation_id` = `EE3_5`.`derivations`.`derivation_id`)))) union (select 'multiple' AS `mode`,group_concat(`EE3_5`.`lemmata`.`modern_lemma` order by `EE3_5`.`multiple_lemmata_analyses`.`part_number` ASC separator ' ') AS `modern_lemma`,group_concat(`EE3_5`.`lemmata`.`lemma_part_of_speech` order by `EE3_5`.`multiple_lemmata_analyses`.`part_number` ASC separator '  ') AS `lemma_part_of_speech`,if(isnull(`EE3_5`.`wordforms`.`wordform`),'',`EE3_5`.`wordforms`.`wordform`) AS `wordform`,group_concat(if(isnull(`EE3_5`.`derivations`.`normalized_form`),'',`EE3_5`.`derivations`.`normalized_form`) order by `EE3_5`.`multiple_lemmata_analyses`.`part_number` ASC separator ' ') AS `normalized_form` from (((`EE3_5`.`lemmata` join `EE3_5`.`multiple_lemmata_analyses`) join (`EE3_5`.`multiple_lemmata_analysis_parts` left join `EE3_5`.`derivations` on((`EE3_5`.`multiple_lemmata_analysis_parts`.`derivation_id` = `EE3_5`.`derivations`.`derivation_id`)))) join (`EE3_5`.`analyzed_wordforms` left join `EE3_5`.`wordforms` on((`EE3_5`.`analyzed_wordforms`.`wordform_id` = `EE3_5`.`wordforms`.`wordform_id`)))) where ((`EE3_5`.`analyzed_wordforms`.`multiple_lemmata_analysis_id` = `EE3_5`.`multiple_lemmata_analyses`.`multiple_lemmata_analysis_id`) and (`EE3_5`.`multiple_lemmata_analyses`.`multiple_lemmata_analysis_part_id` = `EE3_5`.`multiple_lemmata_analysis_parts`.`multiple_lemmata_analysis_part_id`) and (`EE3_5`.`multiple_lemmata_analysis_parts`.`lemma_id` = `EE3_5`.`lemmata`.`lemma_id`)) group by `EE3_5`.`analyzed_wordforms`.`analyzed_wordform_id`,`EE3_5`.`multiple_lemmata_analyses`.`multiple_lemmata_analysis_id`);




CREATE ALGORITHM=UNDEFINED DEFINER=`impact`@`%` SQL SECURITY DEFINER 
VIEW 
	`EE3_5`.`lemmata_and_wordforms_multiple` 
AS select 'multiple' AS `mode`,group_concat(`EE3_5`.`lemmata`.`modern_lemma` order by `EE3_5`.`multiple_lemmata_analyses`.`part_number` ASC separator ' ') AS `modern_lemma`,group_concat(`EE3_5`.`lemmata`.`lemma_part_of_speech` 
order by `EE3_5`.`multiple_lemmata_analyses`.`part_number` ASC separator '  ') AS `lemma_part_of_speech`,group_concat(`EE3_5`.`lemmata`.`gloss` order by `EE3_5`.`multiple_lemmata_analyses`.`part_number` ASC separator '  ') AS `gloss`,if(isnull(`EE3_5`.`wordforms`.`wordform`),'',`EE3_5`.`wordforms`.`wordform`) AS `wordform`,group_concat(if(isnull(`EE3_5`.`derivations`.`normalized_form`),'',`EE3_5`.`derivations`.`normalized_form`) order by `EE3_5`.`multiple_lemmata_analyses`.`part_number` ASC separator ' ') AS `normalized_form`,if(isnull(`EE3_5`.`documents`.`title`),'',`EE3_5`.`documents`.`title`) AS `document_title`,`EE3_5`.`token_attestations`.`document_id` AS `document_id`,`EE3_5`.`token_attestations`.`start_pos` AS `start_pos`,`EE3_5`.`token_attestations`.`end_pos` AS `end_pos`,`EE3_5`.`wordform_groups`.`wordform_group_id` AS `wordform_group_id` from (((`EE3_5`.`lemmata` join `EE3_5`.`multiple_lemmata_analyses`) join (`EE3_5`.`multiple_lemmata_analysis_parts` left join `EE3_5`.`derivations` on((`EE3_5`.`multiple_lemmata_analysis_parts`.`derivation_id` = `EE3_5`.`derivations`.`derivation_id`)))) join ((((`EE3_5`.`analyzed_wordforms` left join `EE3_5`.`wordforms` on((`EE3_5`.`analyzed_wordforms`.`wordform_id` = `EE3_5`.`wordforms`.`wordform_id`))) left join `EE3_5`.`token_attestations` on((`EE3_5`.`analyzed_wordforms`.`analyzed_wordform_id` = `EE3_5`.`token_attestations`.`analyzed_wordform_id`))) left join `EE3_5`.`documents` on((`EE3_5`.`token_attestations`.`document_id` = `EE3_5`.`documents`.`document_id`))) left join `EE3_5`.`wordform_groups` on(((`EE3_5`.`token_attestations`.`document_id` = `EE3_5`.`wordform_groups`.`document_id`) and (`EE3_5`.`token_attestations`.`start_pos` = `EE3_5`.`wordform_groups`.`onset`))))) where ((`EE3_5`.`analyzed_wordforms`.`multiple_lemmata_analysis_id` = `EE3_5`.`multiple_lemmata_analyses`.`multiple_lemmata_analysis_id`)
and (`EE3_5`.`multiple_lemmata_analyses`.`multiple_lemmata_analysis_part_id` = `EE3_5`.`multiple_lemmata_analysis_parts`.`multiple_lemmata_analysis_part_id`) and (`EE3_5`.`multiple_lemmata_analysis_parts`.`lemma_id` = `EE3_5`.`lemmata`.`lemma_id`)) group by `EE3_5`.`analyzed_wordforms`.`analyzed_wordform_id`,`EE3_5`.`multiple_lemmata_analyses`.`multiple_lemmata_analysis_id`,`EE3_5`.`token_attestations`.`attestation_id`;




CREATE ALGORITHM=UNDEFINED DEFINER=`impact`@`%` SQL SECURITY DEFINER VIEW `EE3_5`.`lemmata_and_wordforms_single` AS select 'single' AS `mode`,`EE3_5`.`lemmata`.`modern_lemma` AS `modern_lemma`,`EE3_5`.`lemmata`.`lemma_part_of_speech` AS `lemma_part_of_speech`,`EE3_5`.`lemmata`.`gloss` AS `gloss`,if(isnull(`EE3_5`.`wordforms`.`wordform`),'',`EE3_5`.`wordforms`.`wordform`) AS `wordform`,if(isnull(`EE3_5`.`derivations`.`normalized_form`),'',`EE3_5`.`derivations`.`normalized_form`) AS `normalized_form`,if(isnull(`EE3_5`.`documents`.`title`),'',`EE3_5`.`documents`.`title`) AS `document_title`,`EE3_5`.`token_attestations`.`document_id` AS `document_id`,`EE3_5`.`token_attestations`.`start_pos` AS `start_pos`,`EE3_5`.`token_attestations`.`end_pos` AS `end_pos`,`EE3_5`.`wordform_groups`.`wordform_group_id` AS `wordform_group_id` from ((((((`EE3_5`.`lemmata` left join `EE3_5`.`analyzed_wordforms` on(((`EE3_5`.`analyzed_wordforms`.`multiple_lemmata_analysis_id` = 0) and (`EE3_5`.`analyzed_wordforms`.`lemma_id` = `EE3_5`.`lemmata`.`lemma_id`)))) left join `EE3_5`.`wordforms` on((`EE3_5`.`analyzed_wordforms`.`wordform_id` = `EE3_5`.`wordforms`.`wordform_id`))) left join `EE3_5`.`derivations` on((`EE3_5`.`analyzed_wordforms`.`derivation_id` = `EE3_5`.`derivations`.`derivation_id`))) left join `EE3_5`.`token_attestations` on((`EE3_5`.`analyzed_wordforms`.`analyzed_wordform_id` = `EE3_5`.`token_attestations`.`analyzed_wordform_id`))) left join `EE3_5`.`documents` on((`EE3_5`.`token_attestations`.`document_id` = `EE3_5`.`documents`.`document_id`))) left join `EE3_5`.`wordform_groups` on(((`EE3_5`.`token_attestations`.`document_id` = `EE3_5`.`wordform_groups`.`document_id`) and (`EE3_5`.`token_attestations`.`start_pos` = `EE3_5`.`wordform_groups`.`onset`))));
